// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw6dFEhSs0JjX-7oNFX-EgZm7cZUuBWAk',
    appId: '1:1049927159524:web:4d25fdeff25e8a773ea6f1',
    messagingSenderId: '1049927159524',
    projectId: 'future-9c8da',
    authDomain: 'future-9c8da.firebaseapp.com',
    storageBucket: 'future-9c8da.appspot.com',
    measurementId: 'G-256J3JFMY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjW7844llMhKd0vc70b3eg7FkHy7ftCo4',
    appId: '1:1049927159524:android:05160022c88c87b73ea6f1',
    messagingSenderId: '1049927159524',
    projectId: 'future-9c8da',
    storageBucket: 'future-9c8da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2r4VrfChDyKt_0SgnCqUIcmbnoZtAO2M',
    appId: '1:1049927159524:ios:6027326aa568d2bc3ea6f1',
    messagingSenderId: '1049927159524',
    projectId: 'future-9c8da',
    storageBucket: 'future-9c8da.appspot.com',
    iosClientId: '1049927159524-72v5m444hhaieh2800m8hp0hjpqs7cpq.apps.googleusercontent.com',
    iosBundleId: 'com.example.future',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2r4VrfChDyKt_0SgnCqUIcmbnoZtAO2M',
    appId: '1:1049927159524:ios:6027326aa568d2bc3ea6f1',
    messagingSenderId: '1049927159524',
    projectId: 'future-9c8da',
    storageBucket: 'future-9c8da.appspot.com',
    iosClientId: '1049927159524-72v5m444hhaieh2800m8hp0hjpqs7cpq.apps.googleusercontent.com',
    iosBundleId: 'com.example.future',
  );
}
